name: PrYv Config Leader CI

on:
  pull_request:
    branches: 
      - '*'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.4.1]

    steps:
      - name: Download master branch
        uses: actions/checkout@v2

      - name: Node.js installation
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Npm packages installation
        run: yarn install

      - name: Tests
        run: DEBUG=*git yarn test
