name: Service Config-leader CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.14.2]

    steps:
    - name: Install `just`
      uses: extractions/setup-just@v1

    - name: Download master branch
      uses: actions/checkout@v2

    - name: Install Node.js with version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: just install-stable

    - name: Lint
      run: just lint

    - name: Test
      run: IS_CI=true just test
